spring:
  application:
    name: eureka-client-a
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-lab

eureka:
  client:
    password: password123 # ENC(a+9rePX8LJ8wn6WI5+0GwiPBDuwj0E+9)
    serviceUrl:
      defaultZone: http://eureka:${eureka.client.password}@localhost:8761/eureka/ # 注册中心地址（带认证）
  instance:
    preferIpAddress: true
ribbon:
  serverListRefreshInterval: 5 # 服务列表刷新时间间隔

---
spring:
  cloud:
    loadbalancer:
      clients:
        eureka-client-c: # 服务名需与@LoadBalancerClient的name一致
          static-uris:
            - http://127.0.0.1:8083